data:
  beacon:
    types:
      - "ccc"
      - "aaa"
    push:
      - "ccc"
auth:
  clients:
    server:
      uuid: "123"
      ip: "0.0.0.0/0"
    pc:
      uuid: "456"
      ip: "0.0.0.0/0"
    test.com:
      uuid: "111111"
pusher:
  enable: true
  type: "pushdeer"
  key: "key"
ddns:
  zone: "1.com"
  token: "111"