beacon:
  types:
    - "ccc"
    - "aaa"
auth:
  clients:
    server:
      uuid: "123"
      ip: "0.0.0.0/0"
    pc:
      uuid: "456"
      ip: "0.0.0.0/0"
pusher:
  enable: true
  type: "pushdeer"
  key: "key"
  beacons:
    - "aaa"
